
variable "client_id" {
  type    = string
  default = "${env("ARM_CLIENT_ID")}"
}

variable "client_secret" {
  type    = string
  default = "${env("ARM_CLIENT_SECRET")}"
}

variable "environment_id" {
  type    = string
  default = "${env("ARM_ENVIRONMENT_ID")}"
}

variable "image_version" {
  type    = string
  default = "${env("ARM_IMAGE_VERSION")}"
}

variable "subscription_id" {
  type    = string
  default = "${env("ARM_SUBSCRIPTION_ID")}"
}

variable "tenant_id" {
  type    = string
  default = "${env("ARM_TENANT_ID")}"
}

variable "resource_group" {
  type    = string
  default = "${env("RESOURCE_GROUP")}"
}

variable "storage_account" {
  type    = string
  default = "${env("STORAGE_ACCOUNT")}"
}

source "azure-arm" "autogenerated_1" {
  build_resource_group_name = "${var.resource_group}"
  client_id                 = "${var.client_id}"
  client_secret             = "${var.client_secret}"

  communicator    = "winrm"
  image_offer     = "WindowsServer"
  image_publisher = "MicrosoftWindowsServer"
  image_sku       = "2019-Datacenter-smalldisk"

  capture_container_name = "windows"
  capture_name_prefix    = "WindowsServer2019"
  resource_group_name    = "${var.resource_group}"
  storage_account        = "${var.storage_account}"

  # managed_image_resource_group_name = "${var.resource_group}"
  # managed_image_name                = "WindowsServer2019smalldisk"

  os_disk_size_gb = 40
  os_type         = "Windows"

  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  vm_size         = "Standard_D2_v2"
  winrm_insecure  = true
  winrm_timeout   = "5m"
  winrm_use_ssl   = true
  winrm_username  = "sysadmin"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]
  # fix from https://medium.com/nerd-for-tech/packer-sysprep-error-image-state-undeployable-on-azure-b920ad18f6b0
  provisioner "powershell" {
    script = "scripts/sysprep.ps1"    
  }

}
