
variable "client_id" {
  type    = string
  default = "${env("ARM_CLIENT_ID")}"
}

variable "client_secret" {
  type    = string
  default = "${env("ARM_CLIENT_SECRET")}"
}

variable "environment_id" {
  type    = string
  default = "${env("ARM_ENVIRONMENT_ID")}"
}

variable "image_version" {
  type    = string
  default = "${env("ARM_IMAGE_VERSION")}"
}

variable "ssh_pass" {
  type    = string
  default = "${env("ARM_SSH_PASS")}"
}

variable "ssh_user" {
  type    = string
  default = "centos"
}

variable "subscription_id" {
  type    = string
  default = "${env("ARM_SUBSCRIPTION_ID")}"
}

variable "tenant_id" {
  type    = string
  default = "${env("ARM_TENANT_ID")}"
}

variable "resource_group" {
  type    = string
  default = "${env("RESOURCE_GROUP")}"
}

variable "storage_account" {
  type    = string
  default = "${env("STORAGE_ACCOUNT")}"
}

source "azure-arm" "autogenerated_1" {
  build_resource_group_name = "${var.resource_group}"
  client_id                 = "${var.client_id}"
  client_secret             = "${var.client_secret}"

  image_offer     = "CentOS"
  image_publisher = "OpenLogic"
  image_sku       = "7_8"
  image_version   = "7.8.2021020400"

  capture_container_name = "centos"
  capture_name_prefix    = "packercentos78"
  resource_group_name    = "${var.resource_group}"
  // storage_account        = "vmimagestoragesea"
  storage_account        = "${var.storage_account}"


  os_disk_size_gb = 128
  os_type         = "Linux"

  ssh_password    = "${var.ssh_pass}"
  ssh_pty         = "true"
  ssh_username    = "${var.ssh_user}"
  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  vm_size         = "Standard_D2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'"
    inline          = [
      "yum update -y", 
      "yum install -y centos-release-scl", 
      "yum install -y epel-release", 
      "yum install -y zip", 
      "yum install -y unzip", 
      "yum install -y curl", 
      "yum install -y wget"
    ]
    inline_shebang  = "/bin/sh -x"
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/zarf-binaries.sh"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/local-storage-class.sh"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/rke-binaries.sh"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'"
    inline          = ["yum update -y", "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
    inline_shebang  = "/bin/sh -x"
    skip_clean      = true
  }
}
