
variable "client_id" {
  type    = string
  default = "${env("ARM_CLIENT_ID")}"
}

variable "client_secret" {
  type    = string
  default = "${env("ARM_CLIENT_SECRET")}"
}

variable "environment_id" {
  type    = string
  default = "${env("ARM_ENVIRONMENT_ID")}"
}

variable "image_version" {
  type    = string
  default = "${env("ARM_IMAGE_VERSION")}"
}

variable "ssh_pass" {
  type    = string
  default = "${env("ARM_SSH_PASS")}"
}

variable "ssh_user" {
  type    = string
  default = "ubuntu"
}

variable "subscription_id" {
  type    = string
  default = "${env("ARM_SUBSCRIPTION_ID")}"
}

variable "tenant_id" {
  type    = string
  default = "${env("ARM_TENANT_ID")}"
}

variable "resource_group" {
  type    = string
  default = "${env("RESOURCE_GROUP")}"
}

variable "storage_account" {
  type    = string
  default = "${env("STORAGE_ACCOUNT")}"
}

source "azure-arm" "autogenerated_1" {
  build_resource_group_name = "${var.resource_group}"
  client_id                 = "${var.client_id}"
  client_secret             = "${var.client_secret}"

  image_offer     = "0001-com-ubuntu-server-focal"
  image_publisher = "Canonical"
  image_sku       = "20_04-lts"
  image_version   = "20.04.202210180"

  capture_container_name = "ubuntu"
  capture_name_prefix    = "ubuntu2004opentdf"
  resource_group_name    = "${var.resource_group}"
  storage_account        = "${var.storage_account}"
  

  os_disk_size_gb = 40
  os_type         = "Linux"

  ssh_password    = "${var.ssh_pass}"
  ssh_pty         = "true"
  ssh_username    = "${var.ssh_user}"
  subscription_id = "${var.subscription_id}"
  tenant_id       = "${var.tenant_id}"
  vm_size         = "Standard_D2_v2"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]


  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'"
    inline = [
      "apt-get update",
      "export DEBIAN_FRONTEND=noninteractive && apt-get upgrade -y",
      "apt-get install -y curl wget git zip unzip",
      "apt-get autoremove -y"
    ]
    inline_shebang = "/bin/sh -x"
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/python-debian.sh"]
  }
  
  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/node-debian.sh"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/installprereqsopentdf.sh"]
  }
  
  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/kind.sh"]
  }
  
  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E bash '{{ .Path }}'"
    scripts         = ["${path.root}/scripts/validate-binaries.sh"]
  }

  provisioner "shell" {
    execute_command = "echo '${var.ssh_pass}' | {{ .Vars }} sudo -S -E sh '{{ .Path }}'"
    inline          = ["apt upgrade -y", "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
    inline_shebang  = "/bin/sh -x"
    skip_clean      = true
  }
}
